
export const metadata = {
  title: 'Contact | Aarjav Jain',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>Contact page mai apka swaagat hai{children}</body>
    </html>
  )
}